name: Deploy com Terraform no K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Inicializar o Terraform
        run: terraform init

      - name: Validar configuração
        run: terraform validate

      - name: Aplicar infraestrutura automaticamente
        run: terraform apply -auto-approve
